runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/home.html
  upload: www/home.html

- url: /exercise
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)